version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        - INSTALL_XDEBUG=false
    volumes:
      - ./:/var/www:cached
    user: "1000:0"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/public:cached
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql:cached
    ports:
      - "3306:3306"

volumes:
  dbdata:

networks:
  default:
    external:
      name: fintech
